"""add_scene_scan_log

Revision ID: 549f1516728f
Revises: 9badc5b14667
Create Date: 2026-09-06 21:32:43.216127
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

# Autogenerate renders pgvector column types fully qualified but does not emit
# this import itself; without it the migration fails with NameError.
import pgvector.sqlalchemy
from geoalchemy2 import Geometry

revision: str = '549f1516728f'
down_revision: str | None = '9badc5b14667'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_geospatial_table('scene_scan_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scene_id', sa.Integer(), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.Column('scene_footprint', Geometry(geometry_type='POLYGON', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('acquisition_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('oil_detected', sa.Boolean(), nullable=False),
    sa.Column('detection_confidence', sa.Float(), nullable=True),
    sa.Column('scan_completed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['incidents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['scene_id'], ['sar_scenes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_geospatial_index('idx_scene_scan_log_scene_footprint', 'scene_scan_log', ['scene_footprint'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_index('ix_scene_scan_log_region_time', 'scene_scan_log', ['region_id', 'acquisition_time'], unique=False)
    op.create_index('ix_scene_scan_log_scene', 'scene_scan_log', ['scene_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_scene_scan_log_scene', table_name='scene_scan_log')
    op.drop_index('ix_scene_scan_log_region_time', table_name='scene_scan_log')
    op.drop_geospatial_index('idx_scene_scan_log_scene_footprint', table_name='scene_scan_log', postgresql_using='gist', column_name='scene_footprint')
    op.drop_geospatial_table('scene_scan_log')
    # ### end Alembic commands ###
