"""initial schema

Revision ID: 07e5ad6b979a
Revises: 
Create Date: 2026-08-30 12:56:21.637684
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geometry
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

revision: str = '07e5ad6b979a'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evidence_log',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('stage', sa.String(length=64), nullable=False),
    sa.Column('subject_type', sa.String(length=64), nullable=True),
    sa.Column('subject_id', sa.BigInteger(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('prev_hash', sa.String(length=64), nullable=True),
    sa.Column('entry_hash', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entry_hash')
    )
    op.create_index('ix_evidence_log_stage', 'evidence_log', ['stage'], unique=False)
    op.create_index('ix_evidence_log_subject', 'evidence_log', ['subject_type', 'subject_id'], unique=False)
    op.create_index('ix_evidence_log_ts', 'evidence_log', ['ts'], unique=False)
    op.create_geospatial_table('incidents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('center', Geometry(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('aoi', Geometry(geometry_type='POLYGON', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('validates', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ground_truth', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sources', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_geospatial_index('idx_incidents_aoi', 'incidents', ['aoi'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_geospatial_index('idx_incidents_center', 'incidents', ['center'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_index('ix_incidents_occurred_at', 'incidents', ['occurred_at'], unique=False)
    op.create_table('vessels',
    sa.Column('mmsi', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('imo', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('callsign', sa.String(length=32), nullable=True),
    sa.Column('flag', sa.String(length=64), nullable=True),
    sa.Column('vessel_type', sa.String(length=64), nullable=True),
    sa.Column('length_m', sa.Float(), nullable=True),
    sa.Column('width_m', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('mmsi')
    )
    op.create_index(op.f('ix_vessels_imo'), 'vessels', ['imo'], unique=False)
    op.create_geospatial_table('ais_positions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('mmsi', sa.BigInteger(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('geom', Geometry(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('sog', sa.Float(), nullable=True),
    sa.Column('cog', sa.Float(), nullable=True),
    sa.Column('heading', sa.Float(), nullable=True),
    sa.Column('nav_status', sa.String(length=64), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mmsi', 'ts', 'source', name='uq_ais_positions_mmsi_ts_source')
    )
    op.create_geospatial_index('idx_ais_positions_geom', 'ais_positions', ['geom'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_index('ix_ais_positions_incident', 'ais_positions', ['incident_id'], unique=False)
    op.create_index('ix_ais_positions_mmsi_ts', 'ais_positions', ['mmsi', 'ts'], unique=False)
    op.create_index('ix_ais_positions_ts_brin', 'ais_positions', ['ts'], unique=False, postgresql_using='brin')
    op.create_table('incident_embeddings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=True),
    sa.Column('source_type', sa.String(length=64), nullable=False),
    sa.Column('source_ref', sa.String(length=1024), nullable=True),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_incident_embeddings_incident', 'incident_embeddings', ['incident_id'], unique=False)
    op.create_index('ix_incident_embeddings_vec', 'incident_embeddings', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_geospatial_table('sar_scenes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.String(length=256), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('mission', sa.String(length=32), nullable=True),
    sa.Column('mode', sa.String(length=32), nullable=True),
    sa.Column('polarisation', sa.String(length=32), nullable=True),
    sa.Column('orbit_direction', sa.String(length=32), nullable=True),
    sa.Column('acquired_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('footprint', Geometry(geometry_type='POLYGON', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=True),
    sa.Column('local_path', sa.String(length=1024), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('download_status', sa.String(length=32), nullable=False),
    sa.Column('raw_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id')
    )
    op.create_geospatial_index('idx_sar_scenes_footprint', 'sar_scenes', ['footprint'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_index('ix_sar_scenes_acquired_at', 'sar_scenes', ['acquired_at'], unique=False)
    op.create_index('ix_sar_scenes_incident', 'sar_scenes', ['incident_id'], unique=False)
    op.create_geospatial_table('sar_ship_detections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scene_id', sa.Integer(), nullable=False),
    sa.Column('geom', Geometry(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('length_estimate_m', sa.Float(), nullable=True),
    sa.Column('matched_mmsi', sa.BigInteger(), nullable=True),
    sa.Column('match_distance_m', sa.Float(), nullable=True),
    sa.Column('is_dark', sa.Boolean(), nullable=True),
    sa.Column('model_version', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['scene_id'], ['sar_scenes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_geospatial_index('idx_sar_ship_detections_geom', 'sar_ship_detections', ['geom'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_index('ix_sar_ship_detections_dark', 'sar_ship_detections', ['is_dark'], unique=False)
    op.create_index('ix_sar_ship_detections_scene', 'sar_ship_detections', ['scene_id'], unique=False)
    op.create_geospatial_table('slick_detections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scene_id', sa.Integer(), nullable=False),
    sa.Column('geom', Geometry(geometry_type='MULTIPOLYGON', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('area_sq_km', sa.Float(), nullable=True),
    sa.Column('orientation_deg', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=True),
    sa.Column('domain_gap_flag', sa.Boolean(), nullable=False),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['scene_id'], ['sar_scenes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_geospatial_index('idx_slick_detections_geom', 'slick_detections', ['geom'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_index('ix_slick_detections_detected_at', 'slick_detections', ['detected_at'], unique=False)
    op.create_index('ix_slick_detections_scene', 'slick_detections', ['scene_id'], unique=False)
    op.create_geospatial_table('drift_estimates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slick_detection_id', sa.Integer(), nullable=False),
    sa.Column('method', sa.String(length=64), nullable=False),
    sa.Column('backtrack_hours', sa.Integer(), nullable=False),
    sa.Column('ensemble_size', sa.Integer(), nullable=True),
    sa.Column('origin_polygon', Geometry(geometry_type='MULTIPOLYGON', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('origin_centroid', Geometry(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('window_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('corridor', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('forcing', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['slick_detection_id'], ['slick_detections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_geospatial_index('idx_drift_estimates_origin_centroid', 'drift_estimates', ['origin_centroid'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_geospatial_index('idx_drift_estimates_origin_polygon', 'drift_estimates', ['origin_polygon'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_index('ix_drift_estimates_slick', 'drift_estimates', ['slick_detection_id'], unique=False)
    op.create_table('attribution_candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slick_detection_id', sa.Integer(), nullable=False),
    sa.Column('drift_estimate_id', sa.Integer(), nullable=True),
    sa.Column('mmsi', sa.BigInteger(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('shap_values', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_dark_candidate', sa.Boolean(), nullable=False),
    sa.Column('sar_ship_detection_id', sa.Integer(), nullable=True),
    sa.Column('model_version', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['drift_estimate_id'], ['drift_estimates.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['mmsi'], ['vessels.mmsi'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sar_ship_detection_id'], ['sar_ship_detections.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['slick_detection_id'], ['slick_detections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_attribution_candidates_mmsi', 'attribution_candidates', ['mmsi'], unique=False)
    op.create_index('ix_attribution_candidates_slick', 'attribution_candidates', ['slick_detection_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_attribution_candidates_slick', table_name='attribution_candidates')
    op.drop_index('ix_attribution_candidates_mmsi', table_name='attribution_candidates')
    op.drop_table('attribution_candidates')
    op.drop_index('ix_drift_estimates_slick', table_name='drift_estimates')
    op.drop_geospatial_index('idx_drift_estimates_origin_polygon', table_name='drift_estimates', postgresql_using='gist', column_name='origin_polygon')
    op.drop_geospatial_index('idx_drift_estimates_origin_centroid', table_name='drift_estimates', postgresql_using='gist', column_name='origin_centroid')
    op.drop_geospatial_table('drift_estimates')
    op.drop_index('ix_slick_detections_scene', table_name='slick_detections')
    op.drop_index('ix_slick_detections_detected_at', table_name='slick_detections')
    op.drop_geospatial_index('idx_slick_detections_geom', table_name='slick_detections', postgresql_using='gist', column_name='geom')
    op.drop_geospatial_table('slick_detections')
    op.drop_index('ix_sar_ship_detections_scene', table_name='sar_ship_detections')
    op.drop_index('ix_sar_ship_detections_dark', table_name='sar_ship_detections')
    op.drop_geospatial_index('idx_sar_ship_detections_geom', table_name='sar_ship_detections', postgresql_using='gist', column_name='geom')
    op.drop_geospatial_table('sar_ship_detections')
    op.drop_index('ix_sar_scenes_incident', table_name='sar_scenes')
    op.drop_index('ix_sar_scenes_acquired_at', table_name='sar_scenes')
    op.drop_geospatial_index('idx_sar_scenes_footprint', table_name='sar_scenes', postgresql_using='gist', column_name='footprint')
    op.drop_geospatial_table('sar_scenes')
    op.drop_index('ix_incident_embeddings_vec', table_name='incident_embeddings', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_index('ix_incident_embeddings_incident', table_name='incident_embeddings')
    op.drop_table('incident_embeddings')
    op.drop_index('ix_ais_positions_ts_brin', table_name='ais_positions', postgresql_using='brin')
    op.drop_index('ix_ais_positions_mmsi_ts', table_name='ais_positions')
    op.drop_index('ix_ais_positions_incident', table_name='ais_positions')
    op.drop_geospatial_index('idx_ais_positions_geom', table_name='ais_positions', postgresql_using='gist', column_name='geom')
    op.drop_geospatial_table('ais_positions')
    op.drop_index(op.f('ix_vessels_imo'), table_name='vessels')
    op.drop_table('vessels')
    op.drop_index('ix_incidents_occurred_at', table_name='incidents')
    op.drop_geospatial_index('idx_incidents_center', table_name='incidents', postgresql_using='gist', column_name='center')
    op.drop_geospatial_index('idx_incidents_aoi', table_name='incidents', postgresql_using='gist', column_name='aoi')
    op.drop_geospatial_table('incidents')
    op.drop_index('ix_evidence_log_ts', table_name='evidence_log')
    op.drop_index('ix_evidence_log_subject', table_name='evidence_log')
    op.drop_index('ix_evidence_log_stage', table_name='evidence_log')
    op.drop_table('evidence_log')
    # ### end Alembic commands ###
