"""distinguish scene packaging variants

Revision ID: 9badc5b14667
Revises: 07e5ad6b979a
Create Date: 2026-08-30 13:41:16.972758
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

# Autogenerate renders pgvector column types fully qualified but does not emit
# this import itself; without it the migration fails with NameError.
import pgvector.sqlalchemy


revision: str = '9badc5b14667'
down_revision: str | None = '07e5ad6b979a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sar_scenes', sa.Column('acquisition_key', sa.String(length=256), nullable=True))
    op.add_column('sar_scenes', sa.Column('product_format', sa.String(length=32), nullable=True))
    op.create_index('ix_sar_scenes_acquisition_key', 'sar_scenes', ['acquisition_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sar_scenes_acquisition_key', table_name='sar_scenes')
    op.drop_column('sar_scenes', 'product_format')
    op.drop_column('sar_scenes', 'acquisition_key')
    # ### end Alembic commands ###
